version: '2.1'

services:
  postgres:
    container_name: db
    image: postgres
    volumes:
      - /data/postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - kafka-demo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    container_name: kafkabroker
    image: apache/kafka
    ports:
      - 9092:9092
    networks:
      - kafka-demo
  
  app:
    container_name: app
    build: 
      context: .
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - kafka-demo
    depends_on:
        postgres:
          condition: service_healthy

networks:
  kafka-demo:
    driver: bridge